language: c
compiler:
  - gcc
  - clang

env:
  - VER_NGINX=1.10.3
  - VER_NGINX=1.12.2
  - VER_NGINX=1.14.2
  - VER_NGINX=1.16.1
  - VER_NGINX=1.19.6

sudo: false

addons:
  apt:
    packages:
      - libzmq3-dev

install:
  - mkdir ./vendor && cd ./vendor
  - wget "http://nginx.org/download/nginx-${VER_NGINX}.tar.gz" && tar -xf "nginx-${VER_NGINX}.tar.gz"

  - cd nginx-${VER_NGINX}
  - ./configure --add-module=../..

script: make
